name: Formate Code
on:
  push:
    branches: [main]
  pull_request:
    branches-ignore: [main]
jobs:
  build:
    name: Formate Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Safe Directory
        run: git config --global --add safe.directory /github/workspace
      - name: Auto-Formatter
        uses: mezgoodle/auto-formatter@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
