name: Prettier Check

on: [push, pull_request]

jobs:
  prettier:
    name: Prettier Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--write"
